/**
 * Cross-profile delta log — P3.2.
 *
 * Recalculates every golden fixture under both legacy and MERO and writes
 * a markdown report listing the deltas. NO GATE — this is an audit
 * artefact for humans, not a contract. The fact that legacy and MERO
 * differ is expected by design.
 *
 * Why not assert tolerances ?
 *  - MERO is intentionally a different physics model. Asserting "within
 *    X%" would either be too lax to catch real drift or too tight to
 *    accommodate legitimate model differences.
 *  - The golden contract (`golden.test.ts`) is the legacy non-regression
 *    net. This file's job is visibility, not enforcement.
 *
 * The generated file lives next to the fixtures so it can be reviewed
 * in PRs whenever any moteur-touching change lands.
 */

import { describe, it, expect } from 'vitest';
import { writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { calculateTrajectory } from '@/lib/ballistics';
import { LEGACY_PROFILE, MERO_PROFILE } from '@/lib/ballistics/profiles';
import { GOLDEN_FIXTURES } from './fixtures';
import type { BallisticResult } from '@/lib/types';

interface DeltaRow {
  range: number;
  dropΔ: number;
  holdoverΔ: number;
  holdoverMRADΔ: number;
  velocityΔ: number;
  energyΔ: number;
  windDriftΔ: number;
}

function delta(legacy: BallisticResult, mero: BallisticResult): DeltaRow {
  const r = (n: number) => Math.round(n * 100) / 100;
  return {
    range: legacy.range,
    dropΔ: r(mero.drop - legacy.drop),
    holdoverΔ: r(mero.holdover - legacy.holdover),
    holdoverMRADΔ: r(mero.holdoverMRAD - legacy.holdoverMRAD),
    velocityΔ: r(mero.velocity - legacy.velocity),
    energyΔ: r(mero.energy - legacy.energy),
    windDriftΔ: r(mero.windDrift - legacy.windDrift),
  };
}

function fmtRow(d: DeltaRow): string {
  return `| ${d.range} | ${d.dropΔ} | ${d.holdoverΔ} | ${d.holdoverMRADΔ} | ${d.velocityΔ} | ${d.energyΔ} | ${d.windDriftΔ} |`;
}

describe('cross-profile delta log (informative)', () => {
  it('generates cross-profile-deltas.md without asserting any tolerance', () => {
    const lines: string[] = [
      '# Cross-profile deltas — Legacy vs MERO',
      '',
      '_Auto-generated by `cross-profile.test.ts` on each test run. Informative only — no gate._',
      '',
      '**Reading guide**: each row is `MERO − Legacy`. A positive `dropΔ`',
      'means MERO predicts more drop than legacy at that range. Δ values',
      'are NOT errors against truth; they are the expected divergence',
      'between two physics models that share inputs but not numerics.',
      '',
    ];

    for (const fx of GOLDEN_FIXTURES) {
      const legacyRows = calculateTrajectory({
        ...fx.input,
        engineConfig: LEGACY_PROFILE.config,
      });
      const meroRows = calculateTrajectory({
        ...fx.input,
        engineConfig: MERO_PROFILE.config,
      });

      // Same range grid — both profiles share rangeStep / maxRange.
      const minLen = Math.min(legacyRows.length, meroRows.length);
      const deltas: DeltaRow[] = [];
      for (let i = 0; i < minLen; i++) {
        deltas.push(delta(legacyRows[i], meroRows[i]));
      }

      lines.push(`## ${fx.id}`);
      lines.push('');
      lines.push(`_${fx.description}_`);
      lines.push('');
      lines.push('| range (m) | dropΔ (mm) | holdoverΔ (MOA) | holdoverMRADΔ | velocityΔ (m/s) | energyΔ (J) | windDriftΔ (mm) |');
      lines.push('|---|---|---|---|---|---|---|');
      deltas.forEach((d) => lines.push(fmtRow(d)));
      lines.push('');
    }

    const out = lines.join('\n');
    const target = join(process.cwd(), 'src/lib/__fixtures__/sessions/cross-profile-deltas.md');
    writeFileSync(target, out, 'utf-8');

    // Sanity gate — the file MUST contain at least one delta block per
    // fixture. If a future refactor breaks the engine on MERO config we
    // want this to surface here too, even though we don't gate values.
    expect(out).toContain('# Cross-profile deltas');
    expect(out.split('## ').length).toBeGreaterThanOrEqual(GOLDEN_FIXTURES.length + 1);
  });
});
